# Generated by Django 5.2.4 on 2025-07-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shariah_type', models.CharField(choices=[('Murabaha', 'Murabaha'), ('Ijarah', 'Ijarah'), ('Musharakah', 'Musharakah')], max_length=20)),
                ('origination_date', models.DateField()),
            ],
        ),
    ]
